/* Relatório PDF: altera somente a saída do PDF, sem alterar a interface do site. */
(function(){
  const RED=[220,0,0], DARK=[28,28,30], GRAY=[105,105,112], LIGHT=[247,247,248], MID=[218,219,223], WHITE=[255,255,255];
  const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const money=v=>{const s=String(v||'').replace(/R\$\s*/i,'').replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
  const loadImage=src=>fetch(src,{cache:'no-store'}).then(r=>r.blob()).then(b=>new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(b)}));
  function readRows(){return [...document.querySelectorAll('#resultsBody tr')].map(tr=>{const c=[...tr.children];return{selected:!!c[0]?.querySelector('input')?.checked,status:(c[7]?.textContent||'').trim(),d:c.slice(1,7).map(x=>(x.textContent||'').trim())}})}
  function install(){const b=document.querySelector('#pdfBtn');if(!b||b.dataset.pdfLayout==='1')return;b.dataset.pdfLayout='1';b.addEventListener('click',makePdf,true);b.onclick=null}
  async function makePdf(e){e.preventDefault();e.stopImmediatePropagation();const api=window.jspdf,JsPDF=api?.jsPDF;if(!JsPDF)return alert('A biblioteca de PDF ainda está carregando. Aguarde alguns segundos e tente novamente.');const all=readRows();if(!all.length)return alert('Não há VPOs para gerar o relatório.');const bad=all.filter(x=>/REVISAR|DUPLICADO/i.test(x.status));if(bad.length)return alert(`Existem ${bad.length} VPO(s) com pendências. Revise os registros antes de gerar o PDF.`);const selected=all.filter(x=>x.selected);const items=selected.length?selected:all;const now=new Date();const total=items.reduce((a,x)=>a+money(x.d[5]),0);const doc=new JsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});const W=297,H=210,m=8;let logo=null;try{logo=await loadImage('LOGOTIPO-COSTALOG-versão-2020.png')}catch(_){ }
    const logoW=52, logoH=18;
    function header(){doc.setFillColor(...RED);doc.rect(0,0,W,4,'F');doc.setFillColor(...WHITE);doc.roundedRect(m,8,62,22,2.5,2.5,'F');if(logo)doc.addImage(logo,'PNG',m+5,10,logoW,logoH,undefined,'FAST');doc.setFont('helvetica','bold');doc.setFontSize(18);doc.setTextColor(...DARK);doc.text('RELATÓRIO DE VALE-PEDÁGIO',78,15);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(...GRAY);doc.text('CONVERSOR DE VPOs  •  DOCUMENTO OPERACIONAL',78,21);doc.text(`Gerado em ${now.toLocaleString('pt-BR')}`,78,27);doc.setDrawColor(...MID);doc.line(78,30,W-m,30)}
    function footer(){const y=H-5;doc.setDrawColor(...MID);doc.line(m,y-3,W-m,y-3);doc.setFont('helvetica','normal');doc.setFontSize(6.8);doc.setTextColor(...GRAY);doc.text('Costalog  •  A Logística Ideal',m,y);doc.text(`Página ${doc.internal.getNumberOfPages()}`,W-m,y,{align:'right'})}
    header();
    const cardY=35, gap=3, cardW=(W-2*m-2*gap)/3, cardH=18;[['VPOs PROCESSADAS',String(items.length)],['VALOR TOTAL',brl(total)],['STATUS','CONFERIDO']].forEach((x,i)=>{const xx=m+i*(cardW+gap);doc.setFillColor(...LIGHT);doc.roundedRect(xx,cardY,cardW,cardH,2,2,'F');doc.setFillColor(...RED);doc.rect(xx,cardY,2,cardH,'F');doc.setFont('helvetica','bold');doc.setFontSize(6.5);doc.setTextColor(...GRAY);doc.text(x[0],xx+7,cardY+6.5);doc.setFontSize(i===1?11:10);doc.setTextColor(...DARK);doc.text(x[1],xx+7,cardY+13.5)});
    const head=['DATA DE EMISSÃO','VALE-PEDÁGIO','ID VIAGEM','COMPROVANTE ANTT','PLACA','TOTAL VALE-PEDÁGIO'];
    const body=items.map(x=>[x.d[0]||'—',x.d[1]||'—',x.d[2]||'—',x.d[3]||'—',x.d[4]||'—',brl(money(x.d[5]))]);
    const table={startY:58,margin:{left:m,right:m,top:58,bottom:10},head:[head],body,theme:'grid',styles:{font:'helvetica',fontSize:7.2,textColor:DARK,cellPadding:{top:2.8,right:2.2,bottom:2.8,left:2.2},lineColor:MID,lineWidth:.15,valign:'middle',overflow:'linebreak'},headStyles:{fillColor:DARK,textColor:WHITE,fontStyle:'bold',fontSize:7,halign:'center',cellPadding:{top:3,right:2,bottom:3,left:2}},alternateRowStyles:{fillColor:LIGHT},columnStyles:{0:{cellWidth:38,halign:'center'},1:{cellWidth:35,halign:'center'},2:{cellWidth:36,halign:'center'},3:{cellWidth:75,halign:'center'},4:{cellWidth:34,halign:'center',fontStyle:'bold'},5:{cellWidth:63,halign:'right',fontStyle:'bold'}},didDrawPage:()=>{if(doc.internal.getNumberOfPages()>1)header();footer()}};
    try{if(typeof doc.autoTable==='function')doc.autoTable(table);else if(typeof api.autoTable==='function')api.autoTable(doc,table);else return alert('O componente da tabela PDF não carregou. Atualize a página e tente novamente.')}catch(err){console.error(err);return alert('Não foi possível gerar o PDF: '+err.message)}
    const pages=doc.internal.getNumberOfPages();for(let p=1;p<=pages;p++){doc.setPage(p);footer()}const suffix=selected.length?'_Selecionadas':'';doc.save(`VPOs_Costalog${suffix}_${now.toLocaleDateString('pt-BR').replaceAll('/','-')}.pdf`);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else setTimeout(install,0);
})();
